name: barber
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  cloud_firestore: ^3.1.11
  get: ^4.6.1
  otp_text_field: ^1.1.2
  glyphicon: ^0.2.3
  loading_animation_widget: ^1.1.0+3
  form_field_validator: ^1.1.0
  intl: ^0.17.0
  group_radio_button: ^1.2.0
  dropdown_button2: ^1.2.3
  lottie: ^1.2.2
  firebase_storage: ^10.2.12
  image_picker: ^0.8.5
  cached_network_image: ^3.2.0
  persistent_bottom_nav_bar_v2: ^4.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
